# This is a basic workflow to help you get started with Actions

name: Flavor CI Prod

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: subosito/flutter-action@v1

      # Runs a single command using the runners shell
      - name: Get flutter packages
        run: flutter pub get

      # Runs a set of commands using the runners shell
      - name: Run flutter test
        run: flutter test

      - name: Build apk
        run: flutter build apk --dart-define=flavor=prod

      - name: Upload apk
        uses: actions/upload-artifact@v2
        with:
          name: dev-build
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Deploy to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          file: build/app/outputs/flutter-apk/app-release.apk
          groups: pre-release
